#include "tools.h"
#include <iostream>
using namespace std;

// DO NOT EDIT THIS FILE, WRITE YOUR ANSWERS IN tools.cpp

int main() {
	// Question 1
	// Write a function that prints all values in range for which the sum of all digits is a prime number
	print_digit_sum_being_prime(800, 810);

	// Question 2
	vector<string> countryNames;
	vector<int> codes;
	read_file("countryInfo.txt", countryNames, codes);
	print_code_list(countryNames, codes, 5);

	// Question 3
	// Search for country code, assume the user provides names with first letter capitalized
	print_code_for_country("Turkey", countryNames, codes);
	print_code_for_country("Zambia", countryNames, codes);
	print_code_for_country("Adana", countryNames, codes);

	// Question 4: sort with respect to country code
	sort_codes(countryNames, codes);
	print_code_list(countryNames, codes, 10);

	return 0;
}
